# Generated by Django 5.1.4 on 2024-12-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contact_us_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pdesc', models.CharField(max_length=300)),
                ('ptech', models.CharField(max_length=100)),
                ('purl', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='contact_us',
        ),
    ]
