# Generated by Django 5.1.4 on 2024-12-31 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_detail_delete_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_detail',
            old_name='pdesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='project_detail',
            old_name='pname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project_detail',
            old_name='ptech',
            new_name='tech',
        ),
        migrations.RenameField(
            model_name='project_detail',
            old_name='purl',
            new_name='url',
        ),
    ]
