# Generated by Django 5.1.4 on 2025-01-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_pdesc_project_detail_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.CharField(max_length=500)),
                ('twitter', models.CharField(max_length=500)),
                ('github', models.CharField(max_length=500)),
                ('youtube', models.CharField(max_length=500)),
            ],
        ),
    ]
