# Generated by Django 5.1.4 on 2025-01-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='aboutus',
        ),
    ]
