# Generated by Django 5.1.4 on 2025-01-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_about_aboutus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aboutus',
            new_name='AboutMe',
        ),
    ]
