# Generated by Django 5.1.4 on 2025-01-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_aboutus_aboutme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutMe',
            new_name='Aboutsec',
        ),
        migrations.RenameField(
            model_name='aboutsec',
            old_name='about',
            new_name='content',
        ),
    ]
